import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/notifications/styles.css";
import "@mantine/charts/styles.css";
import "mantine-datatable/styles.css";
import "@mantine/dropzone/styles.css";
import "@mantine/carousel/styles.css";
import "./layout.css";
import "./calendar.css";

import { MantineProvider, mantineHtmlProps } from "@mantine/core";

import { Notifications } from "@mantine/notifications";
import RouterLoadingAnimation from "@/components/RouterLoadingAnimation";
import { theme } from "@/components/MantineThemeConfig";
import { ModalsProvider } from "@mantine/modals";
import Providers from "./v1/Provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "JMVC",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" {...mantineHtmlProps} suppressHydrationWarning>
            <head>
                <meta name="apple-mobile-web-app-title" content="JMVC" />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <MantineProvider theme={theme} defaultColorScheme="light">
                    <ModalsProvider>
                        <ThemeProvider attribute={"class"}>
                            <Notifications position="bottom-right" limit={3} />
                            <RouterLoadingAnimation />
                            <Providers>{children}</Providers>
                        </ThemeProvider>
                    </ModalsProvider>
                </MantineProvider>
            </body>
        </html>
    );
}
