import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";

import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/notifications/styles.css";
import "mantine-datatable/styles.layer.css";

import {
    ColorSchemeScript,
    MantineProvider,
    mantineHtmlProps,
} from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import RouterLoadingAnimation from "@/components/RouterLoadingAnimation";
import { MantineColorsTuple, createTheme } from "@mantine/core";

const myColor: MantineColorsTuple = [
    "#ecf9fe",
    "#d9f0f8",
    "#ade1f3",
    "#81d2ef",
    "#61c4eb",
    "#50bce9",
    "#46b8e9",
    "#39a2cf",
    "#2b90ba",
    "#043343",
];

const theme = createTheme({
    colors: {
        myColor,
    },
});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" {...mantineHtmlProps} suppressHydrationWarning>
            <head>
                <ColorSchemeScript />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <MantineProvider theme={theme}>
                    <ThemeProvider attribute={"class"}>
                        <Notifications position="bottom-right" limit={3} />
                        <RouterLoadingAnimation />
                        {children}
                    </ThemeProvider>
                </MantineProvider>
            </body>
        </html>
    );
}
