name: Veterinary Appointment Cron
on:
    schedule:
        - cron: "*/5 * * * *"
    workflow_dispatch: # Allows you to run it manually for testing

jobs:
    check-expired:
        runs-on: ubuntu-latest
        env:
            CRON_SECRET: ${{ secrets.CRON_SECRET }}
        steps:
            - name: Check Expired Appointment
              run: |
                  curl -L -X GET "https://www.josephmary.me/api/cron/alert" \
                  -H "Authorization: Bearer $CRON_SECRET"
